name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # или master, где хранится код

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (если у тебя сайт на JS/React/Vue)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # для статических сайтов может быть просто: cp -r . public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ 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 }}
          publish_dir: ./build  # путь к твоей папке с готовым сайтом
